title: BAD Story
author: Deutscher

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md

theme: minima

minima:
  skin: auto
  header_pages:
    - index.md

