title: BAD Story
author: Deutscher

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md

theme: minima

show_excerpts: true

minima:
  skin: auto

header_pages:
  - index.md

