title: Being a DIK Story Summary
author:
  name: Deutscher

description: Complete summary of the story of "Being a DIK", divided by episodes

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md

remote_theme: jekyll/minima

show_excerpts: true

minima:
  skin: auto

header_pages:
  - index.md

